name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Check Docker Compose version
        run: docker-compose version

      - name: Build and run containers
        run: docker-compose up -d

      - name: Check container logs
        run: docker-compose logs site

      - name: Wait for website to be available
        run: |
          # Try for up to 10 attempts, waiting 5 seconds between attempts.
          for i in {1..10}; do
            if curl -f http://localhost:4000; then
              echo "Site is up!"
              exit 0
            else
              echo "Site not up yet. Waiting..."
              sleep 5
            fi
          done
          echo "Site did not become available in time."
          exit 1

      - name: Tear down
        run: docker-compose down